In [7]:
import numpy as np
from sklearn import preprocessing

In [8]:
X = np.array([[1.,-1.,2.],
              [2.,0.,0.],
              [0.,1.,-1.]])

In [9]:
x_scaled = preprocessing.scale(X)

In [10]:
x_scaled.mean(axis = 0)
# By default after scaling the mean is set to be 0

array([0., 0., 0.])

In [11]:
x_scaled.std(axis = 0)
# For the same the standard deviation is set to be 1

array([1., 1., 1.])

# Using Standard Scaler

In [12]:
scaler = preprocessing.StandardScaler() #assinging it to the scaler function
scaler.fit(X)

scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [13]:
x_test = [[1,1,0]]
scaler.transform(x_test)

array([[ 0.        ,  1.22474487, -0.26726124]])