In [2]:
import numpy as np

In [3]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,1,1,0]]).T

In [4]:
x,y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([[0],
        [1],
        [1],
        [0]]))

In [5]:
#Activation Function
def sig(z):
    return 1/(1 + np.exp(-z))

In [6]:
# derivation of sig function
def derivativeSig(z):
    return (sig(z) * (1 - sig(z)))

In [7]:
wh = 2 * np.random.random((2,2)) - 1
bh = 2 * np.random.random((1,2)) - 1 
wo = 2 * np.random.random((2,1)) - 1
bo = 2 * np.random.random((1,1)) - 1
wh, bh, wo , bo

(array([[ 0.02964169,  0.75004266],
        [-0.08462486,  0.16573028]]),
 array([[-0.54569649, -0.1513551 ]]),
 array([[ 0.92439563],
        [-0.54468106]]),
 array([[0.46909089]]))

In [15]:
# forward propagation with one hidden layer
output0 = x
inputHidden = np.dot(output0,wh) + bh
outputHidden = sig(inputHidden)
inputLastlayer = np.dot(outputHidden,wo) + bo
output = sig(inputLastlayer)
lr = 0.001
output

array([[0.63563031],
       [0.62620325],
       [0.61374787],
       [0.60464524]])

In [17]:
# now applying the back prop
for iter in range(10000):
    first_term_output_layer = output - y
    second_term_output_layer = derivativeSig(inputLastlayer)
    first_two_output_layer = first_term_output_layer * second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_output_layer , wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    changes_output = np.dot(outputHidden.T,first_two_hidden_layer)
    changes_output_bias = np.sum(first_two_output_layer, axis = 0, keepdims = True)

    changes_hidden = np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_output_layer,axis = 0, keepdims = True)

    wo = wo - lr*changes_output
    bo = bo - lr*changes_output_bias

    wh = wh - lr*changes_hidden
    bh = bh - lr*changes_hidden_bias
output0 = x
inputHidden = np.dot(output0,wh) + bh
outputHidden = sig(inputHidden)
inputLastlayer = np.dot(outputHidden,wo) + bo
output = sig(inputLastlayer)
output

ValueError: shapes (4,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)