In [1]:
import numpy as np

In [2]:
# And Gate
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[0],[0],[1]])

In [3]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
Y

array([[0],
       [0],
       [0],
       [1]])

In [5]:
X.shape, Y.shape

((4, 2), (4, 1))

In [6]:
#Activation Function
def sig(z):
    return 1/(1+np.exp(-z))

In [7]:
#Considering random weights & bias for first hidden layer
# we would require a 2x2 matrix for this case
wh = 2 * np.random.random((2,2)) - 1
# for biases we would create a 1x2 matrix as we have to add the bias to combined x & y
bh = 2 * np.random.random((1,2)) - 1
# making the weights for the output layer 
wo = 2 * np.random.random((2,1)) - 1
# considering bias for the output
bo = 2 * np.random.random((1,1)) - 1
wh, bh, wo , bo

(array([[-0.79795631, -0.08812608],
        [ 0.11276845,  0.59568097]]),
 array([[-0.69191641,  0.40381571]]),
 array([[ 0.45435504],
        [-0.89640344]]),
 array([[-0.93881689]]))

In [9]:
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden,wo) + bo)
output

array([[0.21003274],
       [0.19296166],
       [0.20203743],
       [0.18442311]])