In [1]:
import numpy as np

In [5]:
# And Gate 
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[0],[0],[1]])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [6]:
Y

array([[0],
       [0],
       [0],
       [1]])

In [7]:
X.shape, Y.shape

((4, 2), (4, 1))

In [8]:
# Activation Function
def sig(z):
    return 1/(1 + np.exp(-z))

In [12]:
# Considering random weights and bias
weights  = 2*np.random.random((2,1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.45086966],
        [-0.86773505]]),
 array([-0.09193894]))

In [13]:
output0 = X
output = sig(np.dot(output0,weights) + bias)
output

array([[0.47703144],
       [0.27694347],
       [0.36753447],
       [0.19614832]])